service: lightkasten-backend
useDotenv: true
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x
  region: ap-northeast-2
  environment:
    MONGO_URI: ${env:MONGO_URI}
    JWT_SECRET: ${env:JWT_SECRET}
    ACCESS_KEY_ID : ${env:ACCESS_KEY_ID}
    SECRET_KEY : ${env:SECRET_KEY}
    REGION : ${env:REGION}

plugins:
  - serverless-offline
  - serverless-apigw-binary

functions:
  app:
    handler: index.handler
    events:
      - http:
          path: /
          method: ANY
          cors:
            origin: 'https://lightkasten.link'
            headers:
              - Cookie
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: true
      - http:
          path: /{proxy+} # this matches any path, the token 'any' doesn't mean anything special
          method: ANY
          cors:
            origin: 'https://lightkasten.link'
            headers:
              - Cookie
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: true

custom:
  apigwBinary:
    types: #list of mime-types
      - 'multipart/form-data'
      - 'application/x-www-form-urlencoded'
